<?php include ('aahihh_head.php'); ?>

    <div class="container-fluid">
    <div class="row">    
        <?php include ('gehghh_navegador.php'); ?>

        <div class="col-xs-12 col-sm-8 col-md-8">

                <br>
                <div class="row">
                    <div class="col-xs-8 col-sm-8 col-md-8 col-xs-offset-4 col-sm-offset-4 col-md-offset-4">   
                            
                            <form class="form-inline" role="form" name="formulario" method="GET" action="gehoim_agregar_nueva_sucursal_sucursal_creada.php">
                            <div class="form-group datos_nueva_sucursal">
                                   <label for="dy">Pa&iacute;s:</label>
                                   <br>
                                   <select name="" class="form-control" id="dy" style="width:195px;">
                                       <option value="Colombia">Colombia</option>
                                   </select>
                            </div>
                            <br><br>
                            <div class="form-group datos_nueva_sucursal">
                                   <label for="ci">Ciudad:</label>
                                   <br>
                                   <select name="ciudad" class="form-control" id="ci" style="width:195px;">
                                       <option value="0">-- Seleccionar --</option>
                                       <option value="1" >Abejorral</option>
                                       <option value="2" >Abrego</option>
                                       <option value="3" >Abriaqui</option>
                                       <option value="4" >Acacias</option>
                                       <option value="5" >Acandí</option>
                                       <option value="6" >Acevedo</option>
                                       <option value="7" >Achí</option>
                                       <option value="8" >Agrado</option>
                                       <option value="9" >Agua de Dios</option>
                                       <option value="10" >Aguachica</option>
                                       <option value="11" >Aguada</option>
                                       <option value="12" >Aguadas</option>
                                       <option value="13" >Aguazul</option>
                                       <option value="14" >Agustín Codazzi</option>
                                       <option value="15" >Aipe</option>
                                       <option value="16" >Albán</option>
                                       <option value="17" >Albán (San José)</option>
                                       <option value="18" >Albania</option>
                                       <option value="19" >Albania</option>
                                       <option value="20" >Alcalá</option>
                                       <option value="21" >Aldana</option>
                                       <option value="22" >Alejandría</option>
                                       <option value="23" >Algeciras</option>
                                       <option value="24" >Almaguer</option>
                                       <option value="25" >Almeida</option>
                                       <option value="26" >Alpujarra</option>
                                       <option value="27" >Altamira</option>
                                       <option value="28" >Alto Baudó (Pie de Pato)</option>
                                       <option value="29" >Altos del Rosario</option>
                                       <option value="30" >Alvarado</option>
                                       <option value="31" >Amagá</option>
                                       <option value="32" >Amalfi</option>
                                       <option value="33" >Ambalema</option>
                                       <option value="34" >Anapoima</option>
                                       <option value="35" >Ancuyá</option>
                                       <option value="36" >Andalucía</option>
                                       <option value="37" >Andes</option>
                                       <option value="38" >Angelópolis</option>
                                       <option value="39" >Angostura</option>
                                       <option value="40" >Anolaima</option>
                                       <option value="41" >Anorí</option>
                                       <option value="42" >Anserma</option>
                                       <option value="43" >Ansermanuevo</option>
                                       <option value="44" >Antioquia</option>
                                       <option value="45" >Anzá</option>
                                       <option value="46" >Anzóategui</option>
                                       <option value="47" >Apartadó</option>
                                       <option value="48" >Apía</option>
                                       <option value="49" >Aquitania</option>
                                       <option value="50" >Aracataca</option>
                                       <option value="51" >Aranzazu</option>
                                       <option value="52" >Aratoca</option>
                                       <option value="53" >Arauca</option>
                                       <option value="54" >Arauquita</option>
                                       <option value="55" >Arbeláez</option>
                                       <option value="56" >Arboleda (Berruecos)</option>
                                       <option value="57" >Arboledas</option>
                                       <option value="58" >Arboletes</option>
                                       <option value="59" >Arcabuco</option>
                                       <option value="60" >Arenal</option>
                                       <option value="61" >Argelia</option>
                                       <option value="62" >Argelia</option>
                                       <option value="63" >Argelia</option>
                                       <option value="64" >Ariguaní (El Difícil)</option>
                                       <option value="65" >Arjona</option>
                                       <option value="66" >Armenia</option>
                                       <option value="67" >Armero (Guayabal)</option>
                                       <option value="68" >Arroyohondo</option>
                                       <option value="69" >Astrea</option>
                                       <option value="70" >Ataco</option>
                                       <option value="71" >Atrato (Yuto)</option>
                                       <option value="72" >Ayapel</option>
                                       <option value="73" >Bagadó</option>
                                       <option value="74" >Bahía Solano (Mútis)</option>
                                       <option value="75" >Bajo Baudó (Pizarro)</option>
                                       <option value="76" >Balboa</option>
                                       <option value="77" >Balboa</option>
                                       <option value="78" >Baranoa</option>
                                       <option value="79" >Baraya</option>
                                       <option value="80" >Barbacoas</option>
                                       <option value="81" >Barbosa</option>
                                       <option value="82" >Barbosa</option>
                                       <option value="83" >Barichara</option>
                                       <option value="84" >Barranca de Upía</option>
                                       <option value="85" >Barrancabermeja</option>
                                       <option value="86" >Barrancas</option>
                                       <option value="87" >Barranco de Loba</option>
                                       <option value="88" >Barranquilla</option>
                                       <option value="89" >Becerril</option>
                                       <option value="90" >Belalcázar</option>
                                       <option value="91" >Belén</option>
                                       <option value="92" >Belén</option>
                                       <option value="93" >Belén de los Andaquíes</option>
                                       <option value="94" >Belén de Umbría</option>
                                       <option value="95" >Bello</option>
                                       <option value="96" >Belmira</option>
                                       <option value="97" >Beltrán</option>
                                       <option value="98" >Berbeo</option>
                                       <option value="99" >Betania</option>
                                       <option value="100" >Beteitiva</option>
                                       <option value="101" >Betulia</option>
                                       <option value="102" >Betulia</option>
                                       <option value="103" >Bituima</option>
                                       <option value="104" >Boavita</option>
                                       <option value="105" >Bochalema</option>
                                       <option value="106" >Bojacá</option>
                                       <option value="107" >Bojayá (Bellavista)</option>
                                       <option value="108" >Bolívar</option>
                                       <option value="109" >Bolívar</option>
                                       <option value="110" >Bolívar</option>
                                       <option value="111" >Bolívar</option>
                                       <option value="112" >Bosconia</option>
                                       <option value="113" >Boyacá</option>
                                       <option value="114" >Briseño</option>
                                       <option value="115" >Briseño</option>
                                       <option value="116" >Bucaramanga</option>
                                       <option value="117" >Bucarasica</option>
                                       <option value="118" >Buenaventura</option>
                                       <option value="119" >Buenavista</option>
                                       <option value="120" >Buenavista</option>
                                       <option value="121" >Buenavista</option>
                                       <option value="122" >Buenavista</option>
                                       <option value="123" >Buenos Aires</option>
                                       <option value="124" >Buesaco</option>
                                       <option value="125" >Buga</option>
                                       <option value="126" >Bugalagrande</option>
                                       <option value="127" >Buriticá</option>
                                       <option value="128" >Busbanzá</option>
                                       <option value="129" >Cabrera</option>
                                       <option value="130" >Cabrera</option>
                                       <option value="131" >Cabuyaro</option>
                                       <option value="132" >Cáceres</option>
                                       <option value="133" >Cachipay</option>
                                       <option value="134" >Cáchira</option>
                                       <option value="135" >Cácota</option>
                                       <option value="136" >Caicedo</option>
                                       <option value="137" >Caicedonia</option>
                                       <option value="138" >Caimito</option>
                                       <option value="139" >Cajamarca</option>
                                       <option value="140" >Cajibío</option>
                                       <option value="141" >Cajicá</option>
                                       <option value="142" >Calamar</option>
                                       <option value="143" >Calamar</option>
                                       <option value="144" >Calarcá</option>
                                       <option value="145" >Caldas</option>
                                       <option value="146" >Caldas</option>
                                       <option value="147" >Caldono</option>
                                       <option value="148" >Cali</option>
                                       <option value="149" >California</option>
                                       <option value="150" >Calima (Darién)</option>
                                       <option value="151" >Caloto</option>
                                       <option value="152" >Campamento</option>
                                       <option value="153" >Campo de la Cruz</option>
                                       <option value="154" >Campoalegre</option>
                                       <option value="155" >Campohermoso</option>
                                       <option value="156" >Canalete</option>
                                       <option value="157" >Cañasgordas</option>
                                       <option value="158" >Candelaria</option>
                                       <option value="159" >Candelaria</option>
                                       <option value="160" >Cantagallo</option>
                                       <option value="161" >Cantón de San Pablo</option>
                                       <option value="162" >Caparrapí</option>
                                       <option value="163" >Capitanejo</option>
                                       <option value="164" >Caquetá 18 Florencia</option>
                                       <option value="165" >Cáqueza</option>
                                       <option value="166" >Caracolí</option>
                                       <option value="167" >Caramanta</option>
                                       <option value="168" >Carcasí</option>
                                       <option value="169" >Carepa</option>
                                       <option value="170" >Carmen de Apicalá</option>
                                       <option value="171" >Carmen de Carupa</option>
                                       <option value="172" >Carmen de Viboral</option>
                                       <option value="173" >Carolina</option>
                                       <option value="174" >Cartagena</option>
                                       <option value="175" >Cartagena del Chairá</option>
                                       <option value="176" >Cartago</option>
                                       <option value="177" >Carurú</option>
                                       <option value="178" >Casabianca</option>
                                       <option value="179" >Castilla la Nueva</option>
                                       <option value="180" >Caucasia</option>
                                       <option value="181" >Cepitá</option>
                                       <option value="182" >Cereté</option>
                                       <option value="183" >Cerinza</option>
                                       <option value="184" >Cerrito</option>
                                       <option value="185" >Cerro San Antonio</option>
                                       <option value="186" >Chachagüi</option>
                                       <option value="187" >Chaguaní</option>
                                       <option value="188" >Chalán</option>
                                       <option value="189" >Chameza</option>
                                       <option value="190" >Chaparral</option>
                                       <option value="191" >Charalá</option>
                                       <option value="192" >Charta</option>
                                       <option value="193" >Chía</option>
                                       <option value="194" >Chigorodó</option>
                                       <option value="195" >Chima</option>
                                       <option value="196" >Chima</option>
                                       <option value="197" >Chimichagua</option>
                                       <option value="198" >Chinácota</option>
                                       <option value="199" >Chinavita</option>
                                       <option value="200" >Chinchina</option>
                                       <option value="201" >Chinú</option>
                                       <option value="202" >Chipaque</option>
                                       <option value="203" >Chipatá</option>
                                       <option value="204" >Chiquinquirá</option>
                                       <option value="205" >Chíquiza</option>
                                       <option value="206" >Chiriguaná</option>
                                       <option value="207" >Chiscas</option>
                                       <option value="208" >Chita</option>
                                       <option value="209" >Chitagá</option>
                                       <option value="210" >Chitaranque</option>
                                       <option value="211" >Chivatá</option>
                                       <option value="212" >Chivolo</option>
                                       <option value="213" >Chivor</option>
                                       <option value="214" >Choachí</option>
                                       <option value="215" >Chocontá</option>
                                       <option value="216" >Cicuto</option>
                                       <option value="217" >Ciénaga</option>
                                       <option value="218" >Ciénaga</option>
                                       <option value="219" >Ciénaga de Oro</option>
                                       <option value="220" >Cimitarra</option>
                                       <option value="221" >Circasia</option>
                                       <option value="222" >Cisneros</option>
                                       <option value="223" >Clemencia</option>
                                       <option value="224" >Cocorná</option>
                                       <option value="225" >Coello</option>
                                       <option value="226" >Cogua</option>
                                       <option value="227" >Colombia</option>
                                       <option value="228" >Colón</option>
                                       <option value="229" >Colón (Génova)</option>
                                       <option value="230" >Coloso (Ricaurte)</option>
                                       <option value="231" >Cómbita</option>
                                       <option value="232" >Concepción</option>
                                       <option value="233" >Concepción</option>
                                       <option value="234" >Concordia</option>
                                       <option value="235" >Condoto</option>
                                       <option value="236" >Confines</option>
                                       <option value="237" >Consacá</option>
                                       <option value="238" >Contadero</option>
                                       <option value="239" >Contratación</option>
                                       <option value="240" >Convención</option>
                                       <option value="241" >Copacabana</option>
                                       <option value="242" >Coper</option>
                                       <option value="243" >Córdoba</option>
                                       <option value="244" >Córdoba</option>
                                       <option value="245" >Córdoba</option>
                                       <option value="246" >Corinto</option>
                                       <option value="247" >Coromoro</option>
                                       <option value="248" >Corozal</option>
                                       <option value="249" >Corrales</option>
                                       <option value="250" >Cota</option>
                                       <option value="251" >Cotorra</option>
                                       <option value="252" >Covarachia</option>
                                       <option value="253" >Coyaima</option>
                                       <option value="254" >Cravo Norte</option>
                                       <option value="255" >Cuaspud (Carlosama)</option>
                                       <option value="256" >Cubar</option>
                                       <option value="257" >Cubarral</option>
                                       <option value="258" >Cucaita</option>
                                       <option value="259" >Cucunubá</option>
                                       <option value="260" >Cúcuta</option>
                                       <option value="261" >Cucutilla</option>
                                       <option value="262" >Cuitiva</option>
                                       <option value="263" >Cumaral</option>
                                       <option value="264" >Cumaribo</option>
                                       <option value="265" >Cumbal</option>
                                       <option value="266" >Cumbitará</option>
                                       <option value="267" >Cunday</option>
                                       <option value="268" >Curillo</option>
                                       <option value="269" >Curití</option>
                                       <option value="270" >Curumaní</option>
                                       <option value="271" >Dabeiba</option>
                                       <option value="272" >Dagua</option>
                                       <option value="273" >Dibulla</option>
                                       <option value="274" >Distracción</option>
                                       <option value="275" >Dolores</option>
                                       <option value="276" >Don Matías</option>
                                       <option value="277" >Dos Quebradas</option>
                                       <option value="278" >Duitama</option>
                                       <option value="279" >Durania</option>
                                       <option value="280" >Ebéjico</option>
                                       <option value="281" >El Águila</option>
                                       <option value="282" >El Bagre</option>
                                       <option value="283" >El Banco</option>
                                       <option value="284" >El Cairo</option>
                                       <option value="285" >El Calvario</option>
                                       <option value="286" >El Carmen</option>
                                       <option value="287" >El Carmen</option>
                                       <option value="288" >El Carmen</option>
                                       <option value="289" >El Carmen de Bolívar</option>
                                       <option value="290" >El Castillo</option>
                                       <option value="291" >El Cerrito</option>
                                       <option value="292" >El Charco</option>
                                       <option value="293" >El Cocuy</option>
                                       <option value="294" >El Colegio</option>
                                       <option value="295" >El Copey</option>
                                       <option value="296" >El Doncello</option>
                                       <option value="297" >El Dorado</option>
                                       <option value="298" >El Dovio</option>
                                       <option value="299" >El Espino</option>
                                       <option value="300" >El Guacamayo</option>
                                       <option value="301" >El Guamo</option>
                                       <option value="302" >El Litoral de San Juan</option>
                                       <option value="303" >El Molino</option>
                                       <option value="304" >El Paso</option>
                                       <option value="305" >El Paujil</option>
                                       <option value="306" >El Peñón</option>
                                       <option value="307" >El Peñón</option>
                                       <option value="308" >El Peñón</option>
                                       <option value="309" >El Piñón</option>
                                       <option value="310" >El Playón</option>
                                       <option value="311" >El Retén</option>
                                       <option value="312" >El Retorno</option>
                                       <option value="313" >El Rosal</option>
                                       <option value="314" >El Rosario</option>
                                       <option value="315" >El Tablón</option>
                                       <option value="316" >El Tambo</option>
                                       <option value="317" >El Tambo</option>
                                       <option value="318" >El Tarra</option>
                                       <option value="319" >El Zulia</option>
                                       <option value="320" >Elías</option>
                                       <option value="321" >Encino</option>
                                       <option value="322" >Enciso</option>
                                       <option value="323" >Entrerríos</option>
                                       <option value="324" >Envigado</option>
                                       <option value="325" >Espinal</option>
                                       <option value="326" >Facatativá</option>
                                       <option value="327" >Falán</option>
                                       <option value="328" >Filadelfia</option>
                                       <option value="329" >Filandia</option>
                                       <option value="330" >Firavitoba</option>
                                       <option value="331" >Flandes</option>
                                       <option value="332" >Florencia</option>
                                       <option value="333" >Floresta</option>
                                       <option value="334" >Florián</option>
                                       <option value="335" >Florida</option>
                                       <option value="336" >Floridablanca</option>
                                       <option value="337" >Fómeque</option>
                                       <option value="338" >Fonseca</option>
                                       <option value="339" >Fortul</option>
                                       <option value="340" >Fortul</option>
                                       <option value="341" >Fosca </option>
                                       <option value="342" >Francisco Pizarro</option>
                                       <option value="343" >Fredonia</option>
                                       <option value="344" >Fresno</option>
                                       <option value="345" >Frontino</option>
                                       <option value="346" >Fuente de Oro</option>
                                       <option value="347" >Fundación</option>
                                       <option value="348" >Funes</option>
                                       <option value="349" >Funza</option>
                                       <option value="350" >Fúquene</option>
                                       <option value="351" >Fusagasugá</option>
                                       <option value="352" >Gachalá</option>
                                       <option value="353" >Gachancipá</option>
                                       <option value="354" >Gachantivá</option>
                                       <option value="355" >Gachetá</option>
                                       <option value="356" >Galán</option>
                                       <option value="357" >Galapa</option>
                                       <option value="358" >Galeras (Nueva Granada)</option>
                                       <option value="359" >Gama</option>
                                       <option value="360" >Gamarra</option>
                                       <option value="361" >Gámbita</option>
                                       <option value="362" >Gámeza</option>
                                       <option value="363" >Garagoa</option>
                                       <option value="364" >Garzón</option>
                                       <option value="365" >Génova</option>
                                       <option value="366" >Gigante</option>
                                       <option value="367" >Ginebra</option>
                                       <option value="368" >Giraldo</option>
                                       <option value="369" >Girardot</option>
                                       <option value="370" >Girardota</option>
                                       <option value="371" >Girón</option>
                                       <option value="372" >Gómez Plata</option>
                                       <option value="373" >González</option>
                                       <option value="374" >Gramalote</option>
                                       <option value="375" >Granada</option>
                                       <option value="376" >Granada</option>
                                       <option value="377" >Granada</option>
                                       <option value="378" >Guaca</option>
                                       <option value="379" >Guacamayas</option>
                                       <option value="380" >Guacarí</option>
                                       <option value="381" >Guachetá</option>
                                       <option value="382" >Guachucal</option>
                                       <option value="383" >Guadalupe</option>
                                       <option value="384" >Guadalupe</option>
                                       <option value="385" >Guadalupe</option>
                                       <option value="386" >Guaduas</option>
                                       <option value="387" >Guainía 94 Inírida</option>
                                       <option value="388" >Guaitarilla</option>
                                       <option value="389" >Gualmatán</option>
                                       <option value="390" >Guamal</option>
                                       <option value="391" >Guamal</option>
                                       <option value="392" >Guamo</option>
                                       <option value="393" >Guapi</option>
                                       <option value="394" >Guapotá</option>
                                       <option value="395" >Guarandá</option>
                                       <option value="396" >Guarne</option>
                                       <option value="397" >Guasca</option>
                                       <option value="398" >Guatapé</option>
                                       <option value="399" >Guataquí</option>
                                       <option value="400" >Guatavita</option>
                                       <option value="401" >Guateque</option>
                                       <option value="402" >Guática</option>
                                       <option value="403" >Guavata</option>
                                       <option value="404" >Guaviare 95 San José del Guaviare</option>
                                       <option value="405" >Guayabal de Síquima</option>
                                       <option value="406" >Guayabetal</option>
                                       <option value="407" >Guayatá</option>
                                       <option value="408" >Guepsa</option>
                                       <option value="409" >Guicán</option>
                                       <option value="410" >Gutiérrez</option>
                                       <option value="411" >Hacarí</option>
                                       <option value="412" >Hatillo de Loba</option>
                                       <option value="413" >Hato</option>
                                       <option value="414" >Hato Corozal</option>
                                       <option value="415" >Hatonuevo</option>
                                       <option value="416" >Heliconia</option>
                                       <option value="417" >Herrán</option>
                                       <option value="418" >Herveo</option>
                                       <option value="419" >Hispania</option>
                                       <option value="420" >Hobo</option>
                                       <option value="421" >Honda</option>
                                       <option value="422" >Ibagué</option>
                                       <option value="423" >Icononzo</option>
                                       <option value="424" >Iles</option>
                                       <option value="425" >Imúes</option>
                                       <option value="426" >Inzá</option>
                                       <option value="427" >Ipiales</option>
                                       <option value="428" >Iquira</option>
                                       <option value="429" >Isnos</option>
                                       <option value="430" >Itagüí</option>
                                       <option value="431" >Itsmina</option>
                                       <option value="432" >Ituango</option>
                                       <option value="433" >Iza</option>
                                       <option value="434" >Jambaló</option>
                                       <option value="435" >Jamundí</option>
                                       <option value="436" >Jardín</option>
                                       <option value="437" >Jenesano</option>
                                       <option value="438" >Jericó</option>
                                       <option value="439" >Jericó</option>
                                       <option value="440" >Jerusalén</option>
                                       <option value="441" >Jesús María</option>
                                       <option value="442" >Jordán</option>
                                       <option value="443" >Juan de Acosta</option>
                                       <option value="444" >Junín</option>
                                       <option value="445" >Juradó</option>
                                       <option value="446" >La Apartada (Frontera)</option>
                                       <option value="447" >La Argentina</option>
                                       <option value="448" >La Belleza</option>
                                       <option value="449" >La Calera</option>
                                       <option value="450" >La Capilla</option>
                                       <option value="451" >La Ceja</option>
                                       <option value="452" >La Celia</option>
                                       <option value="453" >La Cruz</option>
                                       <option value="454" >La Cumbre</option>
                                       <option value="455" >La Dorada</option>
                                       <option value="456" >La Esperanza</option>
                                       <option value="457" >La Estrella</option>
                                       <option value="458" >La Florida</option>
                                       <option value="459" >La Gloria</option>
                                       <option value="460" >La Jagua de Ibirico</option>
                                       <option value="461" >La Llanada</option>
                                       <option value="462" >La Macarena</option>
                                       <option value="463" >La Merced</option>
                                       <option value="464" >La Mesa</option>
                                       <option value="465" >La Montañita</option>
                                       <option value="466" >La Palma</option>
                                       <option value="467" >La Paz</option>
                                       <option value="468" >La Paz (Robles)</option>
                                       <option value="469" >La Peña</option>
                                       <option value="470" >La Pintada</option>
                                       <option value="471" >La Plata</option>
                                       <option value="472" >La Playa</option>
                                       <option value="473" >La Primavera</option>
                                       <option value="474" >La Salina</option>
                                       <option value="475" >La Sierra</option>
                                       <option value="476" >La Tebaida</option>
                                       <option value="477" >La Tola</option>
                                       <option value="478" >La Ubita</option>
                                       <option value="479" >La Unión</option>
                                       <option value="480" >La Unión</option>
                                       <option value="481" >La Unión</option>
                                       <option value="482" >La Unión</option>
                                       <option value="483" >La Uribe</option>
                                       <option value="484" >La Vega</option>
                                       <option value="485" >La Vega</option>
                                       <option value="486" >La Victoria</option>
                                       <option value="487" >La Victoria</option>
                                       <option value="488" >La Virginia</option>
                                       <option value="489" >Labateca</option>
                                       <option value="490" >Labranzagrande</option>
                                       <option value="491" >Landázuri</option>
                                       <option value="492" >Lebrija</option>
                                       <option value="493" >Leiva</option>
                                       <option value="494" >Lejanías</option>
                                       <option value="495" >Lenguazaque</option>
                                       <option value="496" >Lérida</option>
                                       <option value="497" >Leticia</option>
                                       <option value="498" >Líbano</option>
                                       <option value="499" >Liborina</option>
                                       <option value="500" >Linares</option>
                                       <option value="501" >Lloró</option>
                                       <option value="502" >López (Micay)</option>
                                       <option value="503" >Lorica</option>
                                       <option value="504" >Los Andes (Sotomayor)</option>
                                       <option value="505" >Los Córdobas</option>
                                       <option value="506" >Los Palmitos</option>
                                       <option value="507" >Los Patios</option>
                                       <option value="508" >Los Santos</option>
                                       <option value="509" >Lourdes</option>
                                       <option value="510" >Luruaco</option>
                                       <option value="511" >Macanal</option>
                                       <option value="512" >Macaravita</option>
                                       <option value="513" >Maceo</option>
                                       <option value="514" >Machetá</option>
                                       <option value="515" >Madrid</option>
                                       <option value="516" >Magangue</option>
                                       <option value="517" >Magüí (Payán)</option>
                                       <option value="518" >Mahates</option>
                                       <option value="519" >Maicao</option>
                                       <option value="520" >Majagual</option>
                                       <option value="521" >Málaga</option>
                                       <option value="522" >Malambo</option>
                                       <option value="523" >Mallama (Piedrancha)</option>
                                       <option value="524" >Manatí</option>
                                       <option value="525" >Manaure</option>
                                       <option value="526" >Manaure Balcón Cesar</option>
                                       <option value="527" >Maní</option>
                                       <option value="528" >Manizales</option>
                                       <option value="529" >Manta</option>
                                       <option value="530" >Manzanares</option>
                                       <option value="531" >Mapiripán</option>
                                       <option value="532" >Margarita</option>
                                       <option value="533" >María la Baja</option>
                                       <option value="534" >Marinilla</option>
                                       <option value="535" >Maripí</option>
                                       <option value="536" >Mariquita</option>
                                       <option value="537" >Marmato</option>
                                       <option value="538" >Marquetalia</option>
                                       <option value="539" >Marsella</option>
                                       <option value="540" >Marulanda</option>
                                       <option value="541" >Matanza</option>
                                       <option value="542" >Medellín</option>
                                       <option value="543" >Medina</option>
                                       <option value="544" >Melgar</option>
                                       <option value="545" >Mercaderes</option>
                                       <option value="546" >Mesetas</option>
                                       <option value="547" >Meta 50 Villavicencio</option>
                                       <option value="548" >Milán</option>
                                       <option value="549" >Miraflores</option>
                                       <option value="550" >Miraflores</option>
                                       <option value="551" >Miranda</option>
                                       <option value="552" >Mistrató</option>
                                       <option value="553" >Mocoa</option>
                                       <option value="554" >Mogotes</option>
                                       <option value="555" >Molagavita</option>
                                       <option value="556" >Momil</option>
                                       <option value="557" >Mompós</option>
                                       <option value="558" >Mongua</option>
                                       <option value="559" >Monguí</option>
                                       <option value="560" >Moniquirá</option>
                                       <option value="561" >Monitos</option>
                                       <option value="562" >Montebello</option>
                                       <option value="563" >Montecristo</option>
                                       <option value="564" >Montelíbano</option>
                                       <option value="565" >Montenegro</option>
                                       <option value="566" >Montería</option>
                                       <option value="567" >Monterrey</option>
                                       <option value="568" >Morales</option>
                                       <option value="569" >Morales</option>
                                       <option value="570" >Morelia</option>
                                       <option value="571" >Morroa</option>
                                       <option value="572" >Mosquera</option>
                                       <option value="573" >Mosquera</option>
                                       <option value="574" >Motavita</option>
                                       <option value="575" >Murillo</option>
                                       <option value="576" >Murindó</option>
                                       <option value="577" >Mutatá</option>
                                       <option value="578" >Mutiscua</option>
                                       <option value="579" >Muzo</option>
                                       <option value="580" >Nariño</option>
                                       <option value="581" >Nariño</option>
                                       <option value="582" >Nátaga</option>
                                       <option value="583" >Natagaima</option>
                                       <option value="584" >Nechí</option>
                                       <option value="585" >Necoclí</option>
                                       <option value="586" >Neira</option>
                                       <option value="587" >Neiva</option>
                                       <option value="588" >Nemocón</option>
                                       <option value="589" >Nilo</option>
                                       <option value="590" >Nimaima</option>
                                       <option value="591" >Nobsa</option>
                                       <option value="592" >Nocaima</option>
                                       <option value="593" >Nóvita</option>
                                       <option value="594" >Nuevo Colón</option>
                                       <option value="595" >Nunchía</option>
                                       <option value="596" >Nuquí</option>
                                       <option value="597" >Obando</option>
                                       <option value="598" >Ocamonte</option>
                                       <option value="599" >Ocaña</option>
                                       <option value="600" >Oiba</option>
                                       <option value="601" >Oicatá</option>
                                       <option value="602" >Olaya</option>
                                       <option value="603" >Olaya</option>
                                       <option value="604" >Onzága</option>
                                       <option value="605" >Oporapa</option>
                                       <option value="606" >Orito</option>
                                       <option value="607" >Orocué</option>
                                       <option value="608" >Ortega</option>
                                       <option value="609" >Ospina</option>
                                       <option value="610" >Otanche</option>
                                       <option value="611" >Ovejas</option>
                                       <option value="612" >Pachavita</option>
                                       <option value="613" >Pacho</option>
                                       <option value="614" >Pácora</option>
                                       <option value="615" >Padilla</option>
                                       <option value="616" >Páez</option>
                                       <option value="617" >Páez (Belalcazar)</option>
                                       <option value="618" >Paicol</option>
                                       <option value="619" >Pailitas</option>
                                       <option value="620" >Paime</option>
                                       <option value="621" >Paipa</option>
                                       <option value="622" >Pajarito</option>
                                       <option value="623" >Palermo</option>
                                       <option value="624" >Palestina</option>
                                       <option value="625" >Palestina</option>
                                       <option value="626" >Palmar</option>
                                       <option value="627" >Palmar de Varela</option>
                                       <option value="628" >Palmas del Socorro</option>
                                       <option value="629" >Palmira</option>
                                       <option value="630" >Palmito</option>
                                       <option value="631" >Palocabildo</option>
                                       <option value="632" >Pamplona</option>
                                       <option value="633" >Pamplonita</option>
                                       <option value="634" >Pandi</option>
                                       <option value="635" >Panqueba</option>
                                       <option value="636" >Páramo</option>
                                       <option value="637" >Paratebueno</option>
                                       <option value="638" >Pasca</option>
                                       <option value="639" >Pasto</option>
                                       <option value="640" >Patía (El Bordo)</option>
                                       <option value="641" >Pauna</option>
                                       <option value="642" >Paya</option>
                                       <option value="643" >Paz de Ariporo</option>
                                       <option value="644" >Paz de Río</option>
                                       <option value="645" >Pedraza</option>
                                       <option value="646" >Pelaya</option>
                                       <option value="647" >Peñol</option>
                                       <option value="648" >Pensilvania</option>
                                       <option value="649" >Peque</option>
                                       <option value="650" >Pereira</option>
                                       <option value="651" >Pesca</option>
                                       <option value="652" >Piamonte</option>
                                       <option value="653" >Pie de Cuesta</option>
                                       <option value="654" >Piedras</option>
                                       <option value="655" >Piendamó</option>
                                       <option value="656" >Pijao</option>
                                       <option value="657" >Pijiño del Carmen</option>
                                       <option value="658" >Pinchote</option>
                                       <option value="659" >Pinillos</option>
                                       <option value="660" >Piojó</option>
                                       <option value="661" >Pisva</option>
                                       <option value="662" >Pital</option>
                                       <option value="663" >Pitalito</option>
                                       <option value="664" >Pivijay</option>
                                       <option value="665" >Planadas</option>
                                       <option value="666" >Planeta Rica</option>
                                       <option value="667" >Plato</option>
                                       <option value="668" >Policarpa</option>
                                       <option value="669" >Polonuevo</option>
                                       <option value="670" >Ponedera</option>
                                       <option value="671" >Popayán</option>
                                       <option value="672" >Pore</option>
                                       <option value="673" >Potosí</option>
                                       <option value="674" >Pradera</option>
                                       <option value="675" >Prado</option>
                                       <option value="676" >Providencia</option>
                                       <option value="677" >Providencia</option>
                                       <option value="678" >Publoviejo</option>
                                       <option value="679" >Pueblo Bello</option>
                                       <option value="680" >Pueblo Nuevo</option>
                                       <option value="681" >Pueblo Rico</option>
                                       <option value="682" >Pueblorrico</option>
                                       <option value="683" >Puente Nacional</option>
                                       <option value="684" >Puerres</option>
                                       <option value="685" >Puerto Asís</option>
                                       <option value="686" >Puerto Berrío</option>
                                       <option value="687" >Puerto Boyacá</option>
                                       <option value="688" >Puerto Caicedo</option>
                                       <option value="689" >Puerto Colombia</option>
                                       <option value="690" >Puerto Concordia</option>
                                       <option value="691" >Puerto Escondido</option>
                                       <option value="692" >Puerto Gaitán</option>
                                       <option value="693" >Puerto Guzmán</option>
                                       <option value="694" >Puerto Leguízamo</option>
                                       <option value="695" >Puerto Libertador</option>
                                       <option value="696" >Puerto Lleras</option>
                                       <option value="697" >Puerto López</option>
                                       <option value="698" >Puerto Nare</option>
                                       <option value="699" >Puerto Nariño</option>
                                       <option value="700" >Puerto Parra</option>
                                       <option value="701" >Puerto Rico</option>
                                       <option value="702" >Puerto Rico</option>
                                       <option value="703" >Puerto Rondón</option>
                                       <option value="704" >Puerto Rondón</option>
                                       <option value="705" >Puerto Salgar</option>
                                       <option value="706" >Puerto Santander</option>
                                       <option value="707" >Puerto Tejada</option>
                                       <option value="708" >Puerto Triunfo</option>
                                       <option value="709" >Puerto Wilches</option>
                                       <option value="710" >Pulí</option>
                                       <option value="711" >Pupiales</option>
                                       <option value="712" >Puracé (Coconuco)</option>
                                       <option value="713" >Purificación</option>
                                       <option value="714" >Purísima</option>
                                       <option value="715" >Quebradanegra</option>
                                       <option value="716" >Quetame</option>
                                       <option value="717" >Quibdó</option>
                                       <option value="718" >Quimbaya</option>
                                       <option value="719" >Quinchia</option>
                                       <option value="720" >Quindío 63 Armenia</option>
                                       <option value="721" >Quípama</option>
                                       <option value="722" >Quipile</option>
                                       <option value="723" >Rafael</option>
                                       <option value="724" >Ragonvalia</option>
                                       <option value="725" >Ramiquirí</option>
                                       <option value="726" >Ráquira</option>
                                       <option value="727" >Recetor</option>
                                       <option value="728" >Regidor</option>
                                       <option value="729" >Remedios</option>
                                       <option value="730" >Remolino</option>
                                       <option value="731" >Repelón</option>
                                       <option value="732" >Restrepo</option>
                                       <option value="733" >Restrepo</option>
                                       <option value="734" >Retiro</option>
                                       <option value="735" >Ricaurte</option>
                                       <option value="736" >Ricaurte</option>
                                       <option value="737" >Río de Oro</option>
                                       <option value="738" >Río Viejo</option>
                                       <option value="739" >Rioblanco</option>
                                       <option value="740" >Riofrío</option>
                                       <option value="741" >Riohacha</option>
                                       <option value="742" >Rionegro</option>
                                       <option value="743" >Rionegro</option>
                                       <option value="744" >Riosucio</option>
                                       <option value="745" >Riosucio</option>
                                       <option value="746" >Risaralda</option>
                                       <option value="747" >Rivera</option>
                                       <option value="748" >Roberto Payán (San José)</option>
                                       <option value="749" >Roldanillo</option>
                                       <option value="750" >Roncesvalles</option>
                                       <option value="751" >Rondón</option>
                                       <option value="752" >Rosas</option>
                                       <option value="753" >Rovira</option>
                                       <option value="754" >Sabalarga</option>
                                       <option value="755" >Sabana de Torres</option>
                                       <option value="756" >Sabanagrande</option>
                                       <option value="757" >Sabanalarga</option>
                                       <option value="758" >Sabanalarga</option>
                                       <option value="759" >Sabaneta</option>
                                       <option value="760" >Saboyá</option>
                                       <option value="761" >Sácama</option>
                                       <option value="762" >Sáchica</option>
                                       <option value="763" >Sahagún</option>
                                       <option value="764" >Saladoblanco</option>
                                       <option value="765" >Salamina</option>
                                       <option value="766" >Salamina</option>
                                       <option value="767" >Salazar</option>
                                       <option value="768" >Saldaña</option>
                                       <option value="769" >Salento</option>
                                       <option value="770" >Salgar</option>
                                       <option value="771" >Samacá</option>
                                       <option value="772" >Samaná</option>
                                       <option value="773" >Samaniego</option>
                                       <option value="774" >Sampués</option>
                                       <option value="775" >San Agustín</option>
                                       <option value="776" >San Alberto</option>
                                       <option value="777" >San Andrés</option>
                                       <option value="778" >San Andrés</option>
                                       <option value="779" >San Andrés</option>
                                       <option value="780" >San Andrés Sotavento</option>
                                       <option value="781" >San Antero</option>
                                       <option value="782" >San Antonio</option>
                                       <option value="783" >San Antonio de Tequendama</option>
                                       <option value="784" >San Benito</option>
                                       <option value="785" >San Benito Abad</option>
                                       <option value="786" >San Bernardo</option>
                                       <option value="787" >San Bernardo</option>
                                       <option value="788" >San Bernardo del Viento</option>
                                       <option value="789" >San Calixto</option>
                                       <option value="790" >San Carlos</option>
                                       <option value="791" >San Carlos</option>
                                       <option value="792" >San Carlos de Guaroa</option>
                                       <option value="793" >San Cayetano</option>
                                       <option value="794" >San Cayetano</option>
                                       <option value="795" >San Cristóbal</option>
                                       <option value="796" >San Diego</option>
                                       <option value="797" >San Eduardo</option>
                                       <option value="798" >San Estanislao</option>
                                       <option value="799" >San Fernando</option>
                                       <option value="800" >San francisco</option>
                                       <option value="801" >San Francisco</option>
                                       <option value="802" >San Francisco</option>
                                       <option value="803" >San Gil</option>
                                       <option value="804" >San Jacinto</option>
                                       <option value="805" >San Jacinto del Cauca</option>
                                       <option value="806" >San Jerónimo</option>
                                       <option value="807" >San Joaquín</option>
                                       <option value="808" >San José</option>
                                       <option value="809" >San José de Miranda</option>
                                       <option value="810" >San José de Montaña</option>
                                       <option value="811" >San José de Pare</option>
                                       <option value="812" >San José del Fragua</option>
                                       <option value="813" >San José del Palmar</option>
                                       <option value="814" >San Juan de Arama</option>
                                       <option value="815" >San Juan de Betulia</option>
                                       <option value="816" >San Juan de Rioseco</option>
                                       <option value="817" >San Juan de Urabá</option>
                                       <option value="818" >San Juan del Cesar</option>
                                       <option value="819" >San Juan Nepomuceno</option>
                                       <option value="820" >San Juanito</option>
                                       <option value="821" >San Lorenzo</option>
                                       <option value="822" >San Luis</option>
                                       <option value="823" >San Luis</option>
                                       <option value="824" >San Luis de Gaceno</option>
                                       <option value="825" >San Luis de Palenque</option>
                                       <option value="826" >San Marcos</option>
                                       <option value="827" >San Martín</option>
                                       <option value="828" >San Martín</option>
                                       <option value="829" >San Martín de Loba</option>
                                       <option value="830" >San Mateo</option>
                                       <option value="831" >San Miguel</option>
                                       <option value="832" >San Miguel</option>
                                       <option value="833" >San Miguel de Sema</option>
                                       <option value="834" >San Onofre</option>
                                       <option value="835" >San Pablo</option>
                                       <option value="836" >San Pablo</option>
                                       <option value="837" >San Pablo de Borbur</option>
                                       <option value="838" >San Pedro</option>
                                       <option value="839" >San Pedro</option>
                                       <option value="840" >San Pedro</option>
                                       <option value="841" >San Pedro de Cartago</option>
                                       <option value="842" >San Pedro de Urabá</option>
                                       <option value="843" >San Pelayo</option>
                                       <option value="844" >San Rafael</option>
                                       <option value="845" >San Roque</option>
                                       <option value="846" >San Sebastián</option>
                                       <option value="847" >San Sebastián de Buuenavista</option>
                                       <option value="848" >San Vicente</option>
                                       <option value="849" >San Vicente de Chucurí</option>
                                       <option value="850" >San Vicente del Caguán</option>
                                       <option value="851" >San Zenón</option>
                                       <option value="852" >Sandoná</option>
                                       <option value="853" >Santa Ana</option>
                                       <option value="854" >Santa Bárbara</option>
                                       <option value="855" >Santa Bárbara</option>
                                       <option value="856" >Santa Bárbara (Iscuandé)</option>
                                       <option value="857" >Santa Catalina</option>
                                       <option value="858" >Santa Cruz (Guachávez)</option>
                                       <option value="859" >Santa Helena del Opón</option>
                                       <option value="860" >Santa Isabel</option>
                                       <option value="861" >Santa Lucía</option>
                                       <option value="862" >Santa María</option>
                                       <option value="863" >Santa María</option>
                                       <option value="864" >Santa Marta</option>
                                       <option value="865" >Santa Rosa</option>
                                       <option value="866" >Santa Rosa</option>
                                       <option value="867" >Santa Rosa de Cabal</option>
                                       <option value="868" >Santa Rosa de Osos</option>
                                       <option value="869" >Santa Rosa de Viterbo</option>
                                       <option value="870" >Santa Rosa del Sur</option>
                                       <option value="871" >Santa Rosalia</option>
                                       <option value="872" >Santa Sofía</option>
                                       <option value="873" >Santafé de Bogotá</option>
                                       <option value="874" >Santana</option>
                                       <option value="875" >Santander de Quilichao</option>
                                       <option value="876" >Santiago</option>
                                       <option value="877" >Santiago</option>
                                       <option value="878" >Santo Domingo</option>
                                       <option value="879" >Santo Tomás</option>
                                       <option value="880" >Santuario</option>
                                       <option value="881" >Santuario</option>
                                       <option value="882" >Sapuyés</option>
                                       <option value="883" >Saravena</option>
                                       <option value="884" >Sardinata</option>
                                       <option value="885" >Sasaima</option>
                                       <option value="886" >Sativanorte</option>
                                       <option value="887" >Sativasur</option>
                                       <option value="888" >Segovia</option>
                                       <option value="889" >Sesquilé</option>
                                       <option value="890" >Sevilla</option>
                                       <option value="891" >Siachoque</option>
                                       <option value="892" >Sibate</option>
                                       <option value="893" >Sibundoy</option>
                                       <option value="894" >Silos</option>
                                       <option value="895" >Silvania</option>
                                       <option value="896" >Silvia</option>
                                       <option value="897" >Simacota</option>
                                       <option value="898" >Simijaca</option>
                                       <option value="899" >Simití</option>
                                       <option value="900" >Sincé</option>
                                       <option value="901" >Sincelejo</option>
                                       <option value="902" >Sipí</option>
                                       <option value="903" >Sitionuevo</option>
                                       <option value="904" >Soacha</option>
                                       <option value="905" >Soatá</option>
                                       <option value="906" >Socha</option>
                                       <option value="907" >Socorro</option>
                                       <option value="908" >Socotá</option>
                                       <option value="909" >Sogamoso</option>
                                       <option value="910" >Solano</option>
                                       <option value="911" >Soledad</option>
                                       <option value="912" >Solita</option>
                                       <option value="913" >Somondoco</option>
                                       <option value="914" >Sonsón</option>
                                       <option value="915" >Sopetrán</option>
                                       <option value="916" >Soplaviento</option>
                                       <option value="917" >Sopó</option>
                                       <option value="918" >Sora</option>
                                       <option value="919" >Soracá</option>
                                       <option value="920" >Sotaquirá</option>
                                       <option value="921" >Sotará (Paispamba)</option>
                                       <option value="922" >Suaita</option>
                                       <option value="923" >Suán</option>
                                       <option value="924" >Suárez</option>
                                       <option value="925" >Suárez</option>
                                       <option value="926" >Suazá</option>
                                       <option value="927" >Subachoque</option>
                                       <option value="928" >Sucre</option>
                                       <option value="929" >Sucre</option>
                                       <option value="930" >Suesca</option>
                                       <option value="931" >Supatá</option>
                                       <option value="932" >Supía</option>
                                       <option value="933" >Suratá</option>
                                       <option value="934" >Susa</option>
                                       <option value="935" >Susacón</option>
                                       <option value="936" >Sutamarchán</option>
                                       <option value="937" >Sutatausa</option>
                                       <option value="938" >Sutatenza</option>
                                       <option value="939" >Tabio</option>
                                       <option value="940" >Tadó</option>
                                       <option value="941" >Talaigua Nuevo</option>
                                       <option value="942" >Tamalameque</option>
                                       <option value="943" >Támara</option>
                                       <option value="944" >Tame</option>
                                       <option value="945" >Támesis</option>
                                       <option value="946" >Taminango</option>
                                       <option value="947" >Tangua</option>
                                       <option value="948" >Tarazá</option>
                                       <option value="949" >Tarqui</option>
                                       <option value="950" >Tarso</option>
                                       <option value="951" >Tasco</option>
                                       <option value="952" >Tatamá</option>
                                       <option value="953" >Tauramena</option>
                                       <option value="954" >Tausa</option>
                                       <option value="955" >Tello</option>
                                       <option value="956" >Tena</option>
                                       <option value="957" >Tenerife</option>
                                       <option value="958" >Tenjo</option>
                                       <option value="959" >Tenza</option>
                                       <option value="960" >Teorama</option>
                                       <option value="961" >Teruel</option>
                                       <option value="962" >Tesalia</option>
                                       <option value="963" >Tibacuy</option>
                                       <option value="964" >Tibaná</option>
                                       <option value="965" >Tibasosa</option>
                                       <option value="966" >Tibiritá</option>
                                       <option value="967" >Tibú</option>
                                       <option value="968" >Tierralta</option>
                                       <option value="969" >Timaná</option>
                                       <option value="970" >Timbío</option>
                                       <option value="971" >Timbiquí</option>
                                       <option value="972" >Tinjacá</option>
                                       <option value="973" >Tipacoque</option>
                                       <option value="974" >Tiquisio (Puerto Rico)</option>
                                       <option value="975" >Titiribí</option>
                                       <option value="976" >Toca</option>
                                       <option value="977" >Tocaima</option>
                                       <option value="978" >Tocancipá</option>
                                       <option value="979" >Toguí</option>
                                       <option value="980" >Toledo</option>
                                       <option value="981" >Toledo</option>
                                       <option value="982" >Tolú</option>
                                       <option value="983" >Toluviejo</option>
                                       <option value="984" >Tona</option>
                                       <option value="985" >Tópaga</option>
                                       <option value="986" >Topaipí</option>
                                       <option value="987" >Toribío</option>
                                       <option value="988" >Toro</option>
                                       <option value="989" >Tota</option>
                                       <option value="990" >Totoro</option>
                                       <option value="991" >Trinidad</option>
                                       <option value="992" >Trujillo</option>
                                       <option value="993" >Tubará</option>
                                       <option value="994" >Tuluá</option>
                                       <option value="995" >Tumaco</option>
                                       <option value="996" >Tunja</option>
                                       <option value="997" >Tunungua</option>
                                       <option value="998" >Túquerres</option>
                                       <option value="999" >Turbaco</option>
                                       <option value="1000" >Turbaná</option>
                                       <option value="1001" >Turbo</option>
                                       <option value="1002" >Turmequé</option>
                                       <option value="1003" >Tuta</option>
                                       <option value="1004" >Tutazá</option>
                                       <option value="1005" >Ubalá</option>
                                       <option value="1006" >Ubaque</option>
                                       <option value="1007" >Ubaté</option>
                                       <option value="1008" >Ulloa</option>
                                       <option value="1009" >Úmbita</option>
                                       <option value="1010" >Une</option>
                                       <option value="1011" >Unguía</option>
                                       <option value="1012" >Uramita</option>
                                       <option value="1013" >Uribía</option>
                                       <option value="1014" >Urrao</option>
                                       <option value="1015" >Urumita</option>
                                       <option value="1016" >Usiacurí</option>
                                       <option value="1017" >Útica</option>
                                       <option value="1018" >Valdivia</option>
                                       <option value="1019" >Valencia</option>
                                       <option value="1020" >Valle de San José</option>
                                       <option value="1021" >Valle de San Juan</option>
                                       <option value="1022" >Valledupar</option>
                                       <option value="1023" >Valparaíso</option>
                                       <option value="1024" >Valparaíso</option>
                                       <option value="1025" >Vaupés 97 Mitú</option>
                                       <option value="1026" >Vegachí</option>
                                       <option value="1027" >Vélez</option>
                                       <option value="1028" >Venadillo</option>
                                       <option value="1029" >Venecia</option>
                                       <option value="1030" >Venecia (Ospina Pérez)</option>
                                       <option value="1031" >Ventaquemada</option>
                                       <option value="1032" >Vergara</option>
                                       <option value="1033" >Versalles</option>
                                       <option value="1034" >Vetas</option>
                                       <option value="1035" >Vianí</option>
                                       <option value="1036" >Vichada 99 Puerto Carreño</option>
                                       <option value="1037" >Victoria</option>
                                       <option value="1038" >Vigía del Fuerte</option>
                                       <option value="1039" >Vijes</option>
                                       <option value="1040" >Villa de Leyva</option>
                                       <option value="1041" >Villa del Rosario</option>
                                       <option value="1042" >Villa Gamuez (La Hormiga)</option>
                                       <option value="1043" >Villa Garzón</option>
                                       <option value="1044" >Villacaro</option>
                                       <option value="1045" >Villagómez</option>
                                       <option value="1046" >Villahermosa</option>
                                       <option value="1047" >Villamaría</option>
                                       <option value="1048" >Villanueva</option>
                                       <option value="1049" >Villanueva</option>
                                       <option value="1050" >Villanueva</option>
                                       <option value="1051" >Villanueva</option>
                                       <option value="1052" >Villapinzón</option>
                                       <option value="1053" >Villarrica</option>
                                       <option value="1054" >Villavieja</option>
                                       <option value="1055" >Villeta</option>
                                       <option value="1056" >Viotá</option>
                                       <option value="1057" >Viracachá</option>
                                       <option value="1058" >Vistahermosa</option>
                                       <option value="1059" >Viterbo</option>
                                       <option value="1060" >Yacopí</option>
                                       <option value="1061" >Yacuanquer</option>
                                       <option value="1062" >Yaguará</option>
                                       <option value="1063" >Yalí</option>
                                       <option value="1064" >Yarumal</option>
                                       <option value="1065" >Yolombó</option>
                                       <option value="1066" >Yondó (Casabe)</option>
                                       <option value="1067" >Yopal</option>
                                       <option value="1068" >Yotoco</option>
                                       <option value="1069" >Yumbo</option>
                                       <option value="1070" >Zambrano</option>
                                       <option value="1071" >Zapatoca</option>
                                       <option value="1072" >Zaragoza 895</option>
                                       <option value="1073" >Zarzal</option>
                                       <option value="1074" >Zetaquirá</option>
                                       <option value="1075" >Zipacón</option>
                                       <option value="1076" >Zipaquirá</option>
                                </select>
                            </div>
                            <br><br>                             
                            <div class="form-group datos_nueva_sucursal">
                                <label for="dd">Nombre de la sucursal:</label>
                                <br>
                                <input type="text" class="form-control" name="" id="dd">
                            </div>
                            <br><br>
                            <div class="form-group datos_nueva_sucursal">
                                <label for="dd">Direcci&oacute;n sucursal:</label>
                                <br>
                                <input type="text" class="form-control" name="" id="dd">
                            </div>
                            <br><br>
                            <div class="form-group datos_nueva_sucursal">
                                <label for="dd">Tel&eacute;fono:</label>
                                <br>
                                <input type="text" class="form-control" name="" id="dd">
                            </div>
                            <br><br>
                            <div class="form-group datos_nueva_sucursal">
                                <label for="dd">Email sucursal:</label>
                                <br>
                                <input type="email" class="form-control" name="" id="dd">
                            </div>
                            <div style="height:33px; float:none; clear:both;"></div>
                            <div>
                            <button type="submit" class="btn btn-primary">Crear sucursal</button>
                            </div>
                        </form>
                </div>
            </div>

        <div style="height:25px; float:none; clear:both;"></div>  
    </div>    
    </div>

<?php include ('aayyhh_footer.php'); ?>       







